### ISSUE TITLE
ping example times out

### ISSUE THREAD

**Issue by coriolinus** [bitmartexchange/bitmart-official-api-docs#11]
The [ping example](https://github.com/bitmartexchange/bitmart-official-api-docs/blob/master/websocket/ping.md) times out instead of returning data. This is not an encouraging start for people attempting to get started with the bitmart websocket service.

Using this script:

```python
# based on https://github.com/bitmartexchange/bitmart-official-api-docs/
#                             blob/master/websocket/ping.md

import json
from websocket import create_connection
from contextlib import closing


def main():
    print("creating websocket connection to bitmart...")
    with closing(create_connection("wss://openws.bitmart.com")) as ws:
        print("sending 'ping' subscription...")
        ws.send('{"subscribe":"ping"}')
        print("waiting for response...")
        data = ws.recv()

    try:
        print(json.loads(data))
    except Exception as e:
        print("json error:", e)
        print(data)


if __name__ == "__main__":
    main()
```

I see these results:

```sh
$ pipenv run example.py 
Fri May  3 10:55:41 CEST 2019
creating websocket connection to bitmart...
Traceback (most recent call last):
  File "example.py", line 25, in <module>
    main()
  File "example.py", line 11, in main
    with closing(create_connection("wss://openws.bitmart.com")) as ws:
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
TimeoutError: [Errno 60] Operation timed out
```

**Comment by coriolinus** [comment]
An even more minimal example of this issue:

```python
Fri May  3 11:04:40 CEST 2019
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from websocket import create_connection
>>> ws = create_connection("wss://openws.bitmart.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/Users/prgn/.local/share/virtualenvs/pyping-XZ_7aXaE/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
TimeoutError: [Errno 60] Operation timed out
```

**Comment by coriolinus** [comment]
The problem isn't with the `websocket-client` library; the same behavior appears with the `websockets` library:

```python
#!/usr/bin/env python3

import asyncio
import json
import websockets

BITMART = "wss://openws.bitmart.com"


async def ping():
    print("creating websocket connection to bitmart...")
    async with websockets.connect(BITMART) as ws:
        print("sending 'ping' subscription...")
        await ws.send('{"subscribe":"ping"}')
        print("waiting for response...")
        data = await ws.recv()

    try:
        print(json.loads(data))
    except Exception as e:
        print("json error:", e)
        print(data)


def main():
    asyncio.run(ping())


if __name__ == "__main__":
    main()
```

At the same time, the problem isn't universal: the following go code works:

```go
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/gorilla/websocket"
)

const bitmart = "wss://openws.bitmart.com"

func check(err error, context string) {
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func main() {
	conn, _, err := websocket.DefaultDialer.Dial(bitmart, nil)
	check(err, "dial")
	defer conn.Close()

	err = conn.WriteMessage(websocket.TextMessage, []byte(`{"subscribe":"ping"}`))
	check(err, "send")

	_, message, err := conn.ReadMessage()
	check(err, "recv")

	var jsdata interface{}
	err = json.Unmarshal(message, &jsdata)
	check(err, "json unmarshal")
	pretty, err := json.MarshalIndent(jsdata, "", "  ")
	check(err, "json remarshal")
	fmt.Printf("%s\n", pretty)
}
```

So, somehow the Bitmart websocket API is _incompatible with Python_.
